### ISSUE TITLE
Login page: X button layout issue

### ISSUE THREAD

**Issue by kate-krasnoselska** [kate-krasnoselska/web.test#11]
'X' should be centered vertically and horizontally inside the button.

Check the screenshot attached.
![Screenshot 2021-03-07 at 10 05 15](https://user-images.githubusercontent.com/57406734/110233593-8ebdee80-7f2d-11eb-8bfc-0149158c1b1a.png)

**Comment by varajan** [comment]
Cannot be fixed.
