### ISSUE TITLE
Login page: Borders color issue

### ISSUE THREAD

**Issue by kate-krasnoselska** [kate-krasnoselska/web.test#14]
Please check the color of the borders. I believe we should use one color for this element. 
Please ask the designer if needed.

Check the screenshot attached.
![Screenshot 2021-03-07 at 10 19 12](https://user-images.githubusercontent.com/57406734/110233763-ec9f0600-7f2e-11eb-98bc-5c6779f864ed.png)

**Comment by varajan** [comment]
Cannot be fixed (default browser behavior)
