### ISSUE TITLE
Login page needs to be prettified 

### ISSUE THREAD

**Issue by kate-krasnoselska** [kate-krasnoselska/web.test#15]
I believe that we need to prettify the Login page layout. All the elements should have the same borders and distances between each other and ends of the screen (left, right, up, bottom).

Please discuss it with the designer if needed

Check the screenshot attached
![Screenshot 2021-03-07 at 10 22 44](https://user-images.githubusercontent.com/57406734/110233870-a7c79f00-7f2f-11eb-9241-a562f31a892e.png)

**Comment by varajan** [comment]
Cannot be fixed, don't have time for this.
