### ISSUE TITLE
Login page: Blue borders issue

### ISSUE THREAD

**Issue by kate-krasnoselska** [kate-krasnoselska/web.test#16]
Active input indicator (blue)borders are too far from grey (normal) input borders (User, Password, Remind password Inputs)

I believe that activated input borders should not be just around grey borders, but exactly ON them.

See screenshots attached.
![Screenshot 2021-03-07 at 10 34 21](https://user-images.githubusercontent.com/57406734/110234097-5f10e580-7f31-11eb-9a79-a1a9d9cca979.png)
![Screenshot 2021-03-07 at 10 34 26](https://user-images.githubusercontent.com/57406734/110234103-620bd600-7f31-11eb-834a-7718a6b24103.png)
![Screenshot 2021-03-07 at 10 34 31](https://user-images.githubusercontent.com/57406734/110234106-63d59980-7f31-11eb-97cc-95cd2e29a522.png)

**Comment by varajan** [comment]
Cannot be fixed (default browser behavior)
