### ISSUE TITLE
Calculator page needs to be prettified 

### ISSUE THREAD

**Issue by kate-krasnoselska** [kate-krasnoselska/web.test#22]
- We need to set all the elements centered and to be inline vertically and horizontally
- I'd like to set the right end of all the lines inline vertically if possible 
Please talk to the designer if needed

Check the screenshot attached
![Screenshot 2021-03-07 at 11 14 59](https://user-images.githubusercontent.com/57406734/110235113-13613a80-7f37-11eb-9ddb-2940c5e2afab.png)

**Comment by varajan** [comment]
Cannot be fixed (don't have time for this)
