### ISSUE TITLE
Question: how to create a page 

### ISSUE THREAD

**Issue by kate-krasnoselska** [kate-krasnoselska/web.test#24]
Sorry, I have forgotten how to add a new page for autotests for the Third page. Could you help me?
![Screenshot 2021-03-07 at 14 50 01](https://user-images.githubusercontent.com/57406734/110240421-7f05d080-7f54-11eb-84cd-3c57977bdf90.png)

**Comment by varajan** [comment]
1. Right-click on project (Calculator.Tests)
2. New -> New Class
3. Set needed name.
![image](https://user-images.githubusercontent.com/30838113/110435885-3cf79e80-80bc-11eb-9f90-372dc9ef244e.png)

**Comment by kate-krasnoselska** [comment]
thanks a lot!
