### ISSUE TITLE
Calculator page: Start Month issue

### ISSUE THREAD

**Issue by kate-krasnoselska** [kate-krasnoselska/web.test#33]
**Branch: bug-fix**

The Month field should be prepopulated with the current month, not the next one

![Screenshot 2021-04-05 at 08 46 31](https://user-images.githubusercontent.com/57406734/113541864-bb782b00-95eb-11eb-83f1-be73eb0cc9ff.png)
Test falls
<img width="953" alt="Screenshot 2021-04-05 at 08 49 37" src="https://user-images.githubusercontent.com/57406734/113541947-e5c9e880-95eb-11eb-94bc-b49d5cf6c93c.png">
Test falls also
<img width="1044" alt="Screenshot 2021-04-05 at 08 59 36" src="https://user-images.githubusercontent.com/57406734/113542612-51f91c00-95ed-11eb-992c-5419f368a707.png">

**Comment by varajan** [comment]
fixed
