### ISSUE TITLE
Calculator page issue: Income & Interest Earned fields issues

### ISSUE THREAD

**Issue by kate-krasnoselska** [kate-krasnoselska/web.test#37]
**Branch: bug-fix**

I believe that the settings page does not work properly.

I as a user can not set a certain data format. Each time data formatting is different, and this program behavior causes autotest falling. I do not know which format to expect each time

Could you please check the data formatting?
See the examples below
<img width="1047" alt="Screenshot 2021-04-05 at 09 33 15" src="https://user-images.githubusercontent.com/57406734/113545239-7acfe000-95f2-11eb-80d1-b88bcb530806.png">

____

**Question to discuss:** how to write the autotest properly and laconic when we know that there are many different data format settings. Using kinda "We are expecting This 'OR' That 'OR' That1 data format"?

**Comment by varajan** [comment]
One of the solutions: before test set the formats. E.g. in SetUp

**Comment by varajan** [comment]
@kate-krasnoselska, please re-test and close if not reproduced.

**Comment by kate-krasnoselska** [comment]
done
