### ISSUE TITLE
Login page: Login field issue

### ISSUE THREAD

**Issue by kate-krasnoselska** [kate-krasnoselska/web.test#39]
**Branch: Login-page-object**

According to the requirements, the login field should be labeled "User"

Autotest falls here
<img width="924" alt="Screenshot 2021-04-07 at 10 23 08" src="https://user-images.githubusercontent.com/57406734/113826976-70951980-978b-11eb-90cf-0c23a3d16eab.png">

**Comment by varajan** [comment]
@kate-krasnoselska, please re-test and close if not reproduced.

**Comment by kate-krasnoselska** [comment]
done
