### ISSUE TITLE
Login page: Password field name issue

### ISSUE THREAD

**Issue by kate-krasnoselska** [kate-krasnoselska/web.test#40]
**Branch: Login-page-object**

According to the requirements, the password field should be labeled "Password", not "Password:"

Autotest falls here
<img width="975" alt="Screenshot 2021-04-07 at 10 26 08" src="https://user-images.githubusercontent.com/57406734/113827308-d41f4700-978b-11eb-8172-0d62cfa13c23.png">

**Comment by varajan** [comment]
@kate-krasnoselska, please re-test and close if not reproduced.

**Comment by kate-krasnoselska** [comment]
done
