### ISSUE TITLE
Login page: Typo

### ISSUE THREAD

**Issue by kate-krasnoselska** [kate-krasnoselska/web.test#41]
**Branch: Login-page-object** 

Please check the remind password button

it should be pasSword
Autotest falls here
<img width="974" alt="Screenshot 2021-04-07 at 10 28 20" src="https://user-images.githubusercontent.com/57406734/113827564-1ea0c380-978c-11eb-9477-e57a82aaf222.png">

**Comment by varajan** [comment]
@kate-krasnoselska, please re-test and close if not reproduced.

**Comment by kate-krasnoselska** [comment]
works fine, thank you
