### ISSUE TITLE
Settings page autotest SelectCurrency: need help

### ISSUE THREAD

**Issue by kate-krasnoselska** [kate-krasnoselska/web.test#44]
Here I have the same question as in SelectNumber case

How to compare these fields, if they have different data?
Do I have to use smth different from assert.areequal? 

assert.true? because I know what to expect when I set $ in settings

![Screenshot 2021-04-12 at 19 54 37](https://user-images.githubusercontent.com/57406734/114432710-a726c600-9bc9-11eb-8ada-7315f27b8db5.png)

**Comment by varajan** [comment]
You can pass few parameters:
```
[TestCase("$ - US dollar", "$")]
public void TestCaseName(sting currencyName, string currencyCode)
```
